import type {
  CookieDefinition,
} from "../../domain/cookie-definition";

export const analyticsCookies: CookieDefinition[] = [
  {
    pattern: "_ga",
    provider: "Google Analytics",
    category: "analytics",
    purpose: "Distinguishes visitors.",
    typicalDuration: "2 years",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_gid",
    provider: "Google Analytics",
    category: "analytics",
    purpose: "Stores visitor identifier.",
    typicalDuration: "24 hours",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_gat",
    provider: "Google Analytics",
    category: "analytics",
    purpose: "Request throttling.",
    typicalDuration: "1 minute",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_ga_*",
    provider: "Google Analytics",
    category: "analytics",
    purpose: "GA4 property cookie.",
    typicalDuration: "2 years",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_clck",
    provider: "Microsoft Clarity",
    category: "analytics",
    purpose: "Persists Clarity user ID.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_clsk",
    provider: "Microsoft Clarity",
    category: "analytics",
    purpose: "Stores page session.",
    typicalDuration: "24 hours",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_hj*",
    provider: "Hotjar",
    category: "analytics",
    purpose: "Heatmaps and recordings.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "mp_*",
    provider: "Mixpanel",
    category: "analytics",
    purpose: "Product analytics.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "amp_*",
    provider: "Amplitude",
    category: "analytics",
    purpose: "Behavior analytics.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_pk_*",
    provider: "Matomo",
    category: "analytics",
    purpose: "Visitor analytics.",
    typicalDuration: "13 months",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "NID",
    provider: "Google",
    category: "analytics",
    purpose: "Google preferences and user tracking.",
    typicalDuration: "6 months",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "1P_JAR",
    provider: "Google",
    category: "analytics",
    purpose: "Google user tracking and ad personalization.",
    typicalDuration: "30 days",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "CONSENT",
    provider: "Google",
    category: "analytics",
    purpose: "Stores Google consent state.",
    typicalDuration: "2 years",
    consentRequired: false,
    party: "third-party",
  },
  {
    pattern: "SOCS",
    provider: "Google",
    category: "necessary",
    purpose: "Stores user cookie consent choices.",
    typicalDuration: "13 months",
    consentRequired: false,
    party: "first-party",
  },
];