import type {
  CookieDefinition,
} from "../../domain/cookie-definition";

export const analyticsCookies: CookieDefinition[] = [
  {
    pattern: "_ga",
    provider: "Google Analytics",
    category: "analytics",
    purpose: "Distinguishes visitors.",
    typicalDuration: "2 years",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_gid",
    provider: "Google Analytics",
    category: "analytics",
    purpose: "Stores visitor identifier.",
    typicalDuration: "24 hours",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_gat",
    provider: "Google Analytics",
    category: "analytics",
    purpose: "Request throttling.",
    typicalDuration: "1 minute",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_ga_*",
    provider: "Google Analytics",
    category: "analytics",
    purpose: "GA4 property cookie.",
    typicalDuration: "2 years",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_clck",
    provider: "Microsoft Clarity",
    category: "analytics",
    purpose: "Persists Clarity user ID.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_clsk",
    provider: "Microsoft Clarity",
    category: "analytics",
    purpose: "Stores page session.",
    typicalDuration: "24 hours",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_hj*",
    provider: "Hotjar",
    category: "analytics",
    purpose: "Heatmaps and recordings.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "mp_*",
    provider: "Mixpanel",
    category: "analytics",
    purpose: "Product analytics.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "amp_*",
    provider: "Amplitude",
    category: "analytics",
    purpose: "Behavior analytics.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_pk_*",
    provider: "Matomo",
    category: "analytics",
    purpose: "Visitor analytics.",
    typicalDuration: "13 months",
    consentRequired: true,
    party: "first-party",
  },
];