import type {
  CookieDefinition,
} from "../../domain/cookie-definition";

export const infrastructureCookies: CookieDefinition[] = [
  {
    pattern: "__cf_bm",
    provider: "Cloudflare",
    category: "necessary",
    purpose: "Bot management.",
    typicalDuration: "30 minutes",
    consentRequired: false,
    party: "first-party",
  },
  {
    pattern: "__cflb",
    provider: "Cloudflare",
    category: "necessary",
    purpose: "Load balancing.",
    typicalDuration: "24 hours",
    consentRequired: false,
    party: "first-party",
  },
  {
    pattern: "cf_clearance",
    provider: "Cloudflare",
    category: "necessary",
    purpose: "Clearance for Turnstile/Security check.",
    typicalDuration: "1 year",
    consentRequired: false,
    party: "first-party",
  },
  {
    pattern: "__stripe_mid",
    provider: "Stripe",
    category: "necessary",
    purpose: "Fraud prevention.",
    typicalDuration: "1 year",
    consentRequired: false,
    party: "first-party",
  },
  {
    pattern: "__stripe_sid",
    provider: "Stripe",
    category: "necessary",
    purpose: "Payment session.",
    typicalDuration: "30 minutes",
    consentRequired: false,
    party: "first-party",
  },
  {
    pattern: "MUID",
    provider: "Microsoft",
    category: "analytics",
    purpose: "Identifies unique web browsers visiting Microsoft sites.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "MUIDB",
    provider: "Microsoft",
    category: "analytics",
    purpose: "Used by Bing/Microsoft for user session tracking.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "_EDGE_V",
    provider: "Microsoft",
    category: "necessary",
    purpose: "Edge/Microsoft browser telemetry.",
    typicalDuration: "Session",
    consentRequired: false,
    party: "first-party",
  },
];