import type {
  CookieDefinition,
} from "../../domain/cookie-definition";

export const marketingCookies: CookieDefinition[] = [
  {
    pattern: "_fbp",
    provider: "Meta Pixel",
    category: "marketing",
    purpose: "Advertising attribution.",
    typicalDuration: "90 days",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "_fbc",
    provider: "Meta Pixel",
    category: "marketing",
    purpose: "Stores ad click.",
    typicalDuration: "90 days",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "_gcl_au",
    provider: "Google Ads",
    category: "marketing",
    purpose: "Conversion tracking.",
    typicalDuration: "90 days",
    consentRequired: true,
    party: "first-party",
  },
  {
    pattern: "_uetvid",
    provider: "Microsoft Advertising",
    category: "marketing",
    purpose: "Visitor tracking.",
    typicalDuration: "16 days",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "_uetsid",
    provider: "Microsoft Advertising",
    category: "marketing",
    purpose: "Session tracking.",
    typicalDuration: "1 day",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "_ttp",
    provider: "TikTok Pixel",
    category: "marketing",
    purpose: "Advertising attribution.",
    typicalDuration: "13 months",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "_pin_unauth",
    provider: "Pinterest Tag",
    category: "marketing",
    purpose: "Pinterest visitor tracking.",
    typicalDuration: "1 year",
    consentRequired: true,
    party: "third-party",
  },
  {
    pattern: "_rdt_uuid",
    provider: "Reddit Pixel",
    category: "marketing",
    purpose: "Advertising attribution.",
    typicalDuration: "90 days",
    consentRequired: true,
    party: "third-party",
  },
];